//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewsPortalEntities : DbContext
    {
        public NewsPortalEntities()
            : base("name=NewsPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<New_info> New_info { get; set; }
        public DbSet<Reacts_info> Reacts_info { get; set; }
        public DbSet<Report_info> Report_info { get; set; }
        public DbSet<User_info> User_info { get; set; }
    }
}
