//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class New_info
    {
        public int CatID { get; set; }
        public string NewsCat { get; set; }
    
        public virtual New_info New_info1 { get; set; }
        public virtual New_info New_info2 { get; set; }
        public virtual Report_info Report_info { get; set; }
    }
}
