//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_info
    {
        public Report_info()
        {
            this.User_info = new HashSet<User_info>();
        }
    
        public int RepoID { get; set; }
        public int NewsID { get; set; }
        public string RepoDate { get; set; }
        public string RepoTime { get; set; }
        public string RepoCat { get; set; }
        public string News { get; set; }
    
        public virtual New_info New_info { get; set; }
        public virtual ICollection<User_info> User_info { get; set; }
    }
}
