//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_info
    {
        public int UserID { get; set; }
        public string Comment { get; set; }
        public string Reacts { get; set; }
        public int NewsID { get; set; }
    
        public virtual Report_info Report_info { get; set; }
    }
}
